# Generated by Django 4.1.1 on 2022-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('men', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='men',
            name='product_image_1',
            field=models.ImageField(blank=True, null=True, upload_to='Product_image_men', verbose_name='Первая Фотография  продукт'),
        ),
        migrations.AlterField(
            model_name='men',
            name='product_image_2',
            field=models.ImageField(blank=True, null=True, upload_to='Product_image_men', verbose_name='Вторая Фотография продукт'),
        ),
        migrations.AlterField(
            model_name='men',
            name='product_image_3',
            field=models.ImageField(blank=True, null=True, upload_to='Product_image_men', verbose_name='Третья Фотография продукт'),
        ),
        migrations.AlterField(
            model_name='men',
            name='product_image_4',
            field=models.ImageField(blank=True, null=True, upload_to='Product_image_men', verbose_name='Четвертая Фотография продукт'),
        ),
    ]
