# Generated by Django 4.1.1 on 2022-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_image_1', models.ImageField(upload_to='slide_image/', verbose_name='Фотография первого слайда')),
                ('name_slide_1', models.CharField(max_length=244, verbose_name='Название первого слайда')),
                ('desc_slide_1', models.TextField(verbose_name='Описание первого слайда')),
                ('slide_image_2', models.ImageField(upload_to='slide_image/', verbose_name='Фотография второго слайда')),
                ('name_slide_2', models.CharField(max_length=244, verbose_name='Название второго слайда')),
                ('desc_slide_2', models.TextField(verbose_name='Описание первого слайда')),
            ],
            options={
                'verbose_name': 'Слайды',
                'verbose_name_plural': 'Слайды',
            },
        ),
    ]
