# Generated by Django 4.1.1 on 2022-12-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_women'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.ImageField(upload_to='banner_image', verbose_name='Первая фотография банера!')),
                ('image_2', models.ImageField(upload_to='banner_image', verbose_name='Вторая фотография банера!')),
                ('image_3', models.ImageField(upload_to='banner_image', verbose_name='Третья фотография банера!')),
                ('image_4', models.ImageField(upload_to='banner_image', verbose_name='Четвертая фотография банера!')),
            ],
            options={
                'verbose_name': 'Баннер',
                'verbose_name_plural': 'Баннер',
            },
        ),
    ]
