# Generated by Django 4.1.1 on 2022-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефонный номер ')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('whatsapp', models.URLField(blank=True, null=True, verbose_name='Whatsapp')),
            ],
        ),
    ]
