# Generated by Django 4.1.1 on 2022-12-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_contacts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакты', 'verbose_name_plural': 'Контакты'},
        ),
    ]
