# Generated by Django 4.1.1 on 2022-12-05 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0008_contact_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
        migrations.DeleteModel(
            name='Contact_detail',
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.DeleteModel(
            name='Men',
        ),
        migrations.DeleteModel(
            name='Slide',
        ),
        migrations.DeleteModel(
            name='Women',
        ),
    ]
